---
name: Self
on: [push, pull_request]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - if: ${{ matrix.os == 'windows-latest' }}
        run: shfmt.exe -d test.bash
      - if: ${{ matrix.os != 'windows-latest' }}
        run: shfmt -d test.bash
